# Generated by Django 2.2.4 on 2020-12-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_effectiveness',
            field=models.FloatField(default=0.0),
        ),
    ]
